apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"  # 0.1 CPU core (required for HPA)
            memory: "64Mi"  # Optional but recommended
          limits:
            cpu: "200m"  # Optional (prevents a pod from using too much CPU)
            memory: "128Mi"  # Optional


















